package main

import "os"

// A Provider is an LLM API vendor. Whether a provider is usable is decided by
// which API-key env vars are set (runBootCamp exports one per gitignored key
// file: claude.key, deepseek.key). A provider without a key simply doesn't
// appear in the model dropdown.
type Provider struct {
	ID        string
	KeyEnv    string // environment variable holding the API key
	URL       string // streaming chat endpoint
	Style     string // wire format: styleAnthropic or styleOpenAI
	MaxTokens int    // per-response output cap this provider accepts
}

const (
	styleAnthropic = "anthropic" // Anthropic Messages API SSE events
	styleOpenAI    = "openai"    // OpenAI-compatible chat-completions SSE (DeepSeek)
)

var providers = map[string]Provider{
	"anthropic": {
		ID:     "anthropic",
		KeyEnv: "ANTHROPIC_API_KEY",
		URL:    "https://api.anthropic.com/v1/messages",
		Style:  styleAnthropic,
		// Needs headroom for a full lesson, plus extra because the newer
		// models (Fable, Sonnet 5) spend part of this budget on internal
		// "thinking" tokens before any text comes out.
		MaxTokens: 16384,
	},
	"deepseek": {
		ID:     "deepseek",
		KeyEnv: "DEEPSEEK_API_KEY",
		URL:    "https://api.deepseek.com/chat/completions",
		Style:  styleOpenAI,
		// DeepSeek rejects max_tokens above 8192.
		MaxTokens: 8192,
	},
}

// A Model is one entry in the UI's model dropdown. ID is the exact string the
// provider's API expects; it is also folded into lesson-cache keys so each
// model generates and caches its own content (see modelCacheKey in cache.go).
type Model struct {
	ID       string `json:"id"`
	Name     string `json:"name"` // display label for the dropdown
	Provider string `json:"provider"`
}

// modelCatalog lists every model the app knows about, in dropdown order.
var modelCatalog = []Model{
	{ID: "claude-opus-4-8", Name: "Claude Opus 4.8", Provider: "anthropic"},
	{ID: "claude-fable-5", Name: "Claude Fable 5", Provider: "anthropic"},
	{ID: "claude-sonnet-5", Name: "Claude Sonnet 5", Provider: "anthropic"},
	{ID: "deepseek-chat", Name: "DeepSeek Chat", Provider: "deepseek"},
	{ID: "deepseek-reasoner", Name: "DeepSeek Reasoner", Provider: "deepseek"},
}

// defaultModelID is what every user gets until they pick something else. It
// also owns the cache entries written before models were configurable — all
// of those were generated by this (then-hardcoded) model. Keep it in
// modelCatalog.
const defaultModelID = "claude-opus-4-8"

func modelByID(id string) (Model, bool) {
	for _, m := range modelCatalog {
		if m.ID == id {
			return m, true
		}
	}
	return Model{}, false
}

// modelAvailable reports whether a model's provider has an API key configured.
func modelAvailable(m Model) bool {
	return os.Getenv(providers[m.Provider].KeyEnv) != ""
}

// availableModels returns the catalog filtered to providers with an API key.
func availableModels() []Model {
	out := []Model{}
	for _, m := range modelCatalog {
		if modelAvailable(m) {
			out = append(out, m)
		}
	}
	return out
}
